/*
	The Space Pirate
	Caster
	
	Outlawdy Starswell
*/

Class TSP_CasterShell play
{
	virtual State GetFireState (TSP_Weapon_Caster weapon)
	{
		Console.printf("Your shell didn't do shit lul");
		return weapon.resolveState(null);
	}
}

Class TSP_CasterShellKeeper : Inventory
{
	Array<TSP_CasterShell> shells;
	
	bool, State UseShell (TSP_Weapon_Caster weapon)
	{
		if ( shells.Size() <= 0 )
		{
			Console.Printf("no shells lul");
			return false, weapon.resolveState(null);
		}
		
		let shell = shells[0];
		shells.Delete(0);
		return true, shell.GetFireState(weapon);
	}
	
	void GiveShell(Class<TSP_CasterShell> type)
	{
		TSP_CasterShell shell = TSP_CasterShell(new(type));
		shells.Push(shell);
	}
}

Class TSP_Weapon_Caster : TSP_BaseWeapon
{
	action State A_TSP_FireCaster()
	{
		let shells = TSP_CasterShellKeeper(invoker.owner.FindInventory("TSP_CasterShellKeeper"));
		bool used;
		State fireState;
		[used, fireState] = shells.UseShell(invoker);
		
		if ( !used )
		{
			return resolveState(null);
		}
		
		return fireState;
	}
	
	override void AttachToOwner(Actor other)
	{
		super.AttachToOwner(other);
		// This block is only run if the item got
		// successfully placed in the other's
		// inventory:
		if (owner)
		{
			owner.GiveInventory("TSP_CasterShellKeeper", 1);
			let shells = TSP_CasterShellKeeper(owner.FindInventory("TSP_CasterShellKeeper"));
			
			for ( int i = 0; i < 5; i++ )
			{
				shells.GiveShell("TSP_CasterShell_SpectralBeam");
			}
		}
	}
	
	States
	{
		Select:
			161G A 1 A_Raise();
			Wait;
		Deselect:
			161G A 1 A_TSP_Deselect();
			Wait;
		Ready:
			161G A 1
			{
				invoker.LookScale = 1.0;
				A_WeaponReady();
			}
			Loop;
		Fire:
			161G A 5 A_TSP_FireCaster();
			Goto Ready;
		
		Anim_Fire:
			TNT1 A 0
			{
				TSP_ViewRecoil recoil;
				
				recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.pitch = -0.2;
				recoil.roll = 0.1;
				recoil.roll_shake = 0.1;
				recoil.roll_speed = 50.0;
				A_TSP_AddRecoil(recoil);
				
				recoil = new("TSP_ViewRecoil");
				recoil.shake_amount = 0.1;
				recoil.fadeout = 4;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(8.37, 41.99);
			TNT1 A 1 A_WeaponOffset(16.75, 56.39);
			TNT1 A 1 A_WeaponOffset(16.41, 53.10);
			TNT1 A 1 A_WeaponOffset(14.74, 46.95);
			TNT1 A 1 A_WeaponOffset(10.44, 41.30);
			TNT1 A 1 A_WeaponOffset(6.81, 38.22);
			TNT1 A 1 A_WeaponOffset(4.65, 36.31);
			TNT1 A 1 A_WeaponOffset(3.22, 35.01);
			TNT1 A 1 A_WeaponOffset(2.22, 34.08);
			TNT1 A 1 A_WeaponOffset(1.49, 33.40);
			TNT1 A 1 A_WeaponOffset(0.96, 32.90);
			TNT1 A 1 A_WeaponOffset(0.57, 32.54);
			TNT1 A 1 A_WeaponOffset(0.30, 32.28);
			TNT1 A 1 A_WeaponOffset(0.13, 32.12);
			Stop;
	}
}