Class TSP_Caster_ProtonBeam : Actor
{
	Default
	{
		RenderStyle "Add";
		+BRIGHT
	}
	
	States
	{
		Spawn:
			POSS A -1;
			Stop;
	}
	
	override void Tick()
	{
		if ( !target ) return;
		
		angle = target.angle;
		pitch = target.pitch + 90;
		
		Vector3 spawnPos = (target.pos.x, target.pos.y, target.player.viewz);
	
		Quat base = Quat.FromAngles(target.angle + target.viewangle, target.pitch + target.viewpitch, target.roll);
		Vector3 forward = (1,0,0);
		
		/*Quat offset = Quat.AxisAngle((0,0,1), spreadX*cos(rot));
		offset = offset * Quat.AxisAngle((0,1,0), spreadY*sin(rot));
		Vector3 dir = base * offset * forward;*/
		Vector3 tracerPos = spawnPos + (base * (4,-1,-1));
		
		SetOrigin(tracerPos, true);
				
		FLineTraceData tr;
		target.LineTrace(target.angle, PLAYERMISSILERANGE, target.pitch, flags: TRF_ABSPOSITION, offsetz: tracerPos.z, offsetforward: tracerPos.x, offsetside: tracerPos.y, data: tr);
		scale.y = tr.Distance / 32.;
		
		scale.x = (scale.y / 2.) + frandom(-0.1,0.1);//0.05;
	}
}

Extend Class TSP_Weapon_Caster
{
	double proton_mult;
	
	States
	{
		Fire_ProtonCannon:
			161G A 24
			{
				A_StartSound("caster/proton/charge", CHAN_WEAPON);
				
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 20;
				recoil.fadeout = 4;
				recoil.pitch_shake = 0.3;
				recoil.pitch_speed = 25;
				recoil.roll_shake = 0.3;
				recoil.roll_speed = 35;
				A_TSP_AddRecoil(recoil);
			}
			161G A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.duration = 50;
				recoil.fadeout = 10;
				recoil.yaw_shake = 0.6;
				recoil.yaw_speed = 15;
				recoil.pitch_shake = 0.6;
				recoil.pitch_speed = 30;
				recoil.roll_shake = 0.5;
				recoil.roll_speed = 80;
				A_TSP_AddRecoil(recoil);
				A_StartSound("caster/proton/laser", 45);
				A_Caster_StartProtonBeam();
			}
			161G AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
			{
				invoker.LookScale = 0.25;
				A_Caster_ProtonCannon();
			}
			161G A 0
			{
				invoker.LookScale = 1.0;
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 1;
				recoil.fadeout = 35;
				recoil.pitch = -2.0;
				recoil.roll = -1;
				recoil.roll_shake = 0.2;
				recoil.roll_speed = 55;
				A_TSP_AddRecoil(recoil);
				
				A_Caster_StopProtonBeam();
			}
			161G A 35 A_Overlay(PSP_WEAPONANIM, "Anim_Fire");
			Goto Ready;
	}
	
	TSP_Caster_ProtonBeam beam;
	
	action void A_Caster_StartProtonBeam()
	{
		invoker.beam = TSP_Caster_ProtonBeam(Spawn("TSP_Caster_ProtonBeam"));
		invoker.beam.target = invoker.owner;
		invoker.beam.scale.x = 0.5;
		invoker.beam.Tick();
		invoker.beam.Prev = invoker.beam.pos;
		invoker.proton_mult = 1.0;
	}
	
	action void A_Caster_StopProtonBeam()
	{
		if ( !invoker.beam ) return;
		invoker.beam.Destroy();
	}
	
	action void A_Caster_ProtonCannon()
	{
		//A_TSP_FireBullets(16, 16, 1, 1);
		Actor src = invoker.owner;
		Vector3 spawnPos = (src.pos.x, src.pos.y, src.player.viewz);
			
		BlockThingsIterator it = BlockThingsIterator.Create(self, 2048);
		Actor mo;
		bool hitSomething;
		
		let tracer = new('TSP_MeleeTracer');
			
		while ( it.Next() )
		{
			mo = it.thing;
			
			if ( mo == src ) continue;
			
			if ( !mo.bShootable || mo.bDormant || mo.Health <= 0 ) continue;
			if ( AbsAngle(src.angle, src.AngleTo(mo)) > 15 ) continue;
			if ( AbsAngle(src.pitch, src.PitchTo(mo, zOfs: src.height/2, targZOfs: mo.height/2)) > 15 ) continue;
			
			tracer.toFind = mo;
			tracer.Trace(src.pos + (0,0,src.height/2), src.cursector, (mo.pos - src.pos).Unit(), 2048, TRACE_HitSky, Line.ML_BLOCKEVERYTHING, false, self);
			let res = tracer.results;
			
			if ( res.HitActor == null ) continue;
			if ( res.HitActor != mo ) continue;
			
			mo.DamageMobj(src, src, int(20.0*invoker.proton_mult), damageType);
			for ( int i = 0; i < 3; i++ )
			{
				Vector3 bloodPos = mo.pos + (frandom(-mo.radius, mo.radius), frandom(-mo.radius, mo.radius), frandom(0, mo.height));
				mo.SpawnBlood(bloodPos, 0, 13);
			}
			mo.TriggerPainChance(damageType, true);
			mo.A_StartSound("melee/basic/normal/impact", CHAN_BODY, volume: frandom(0.6,0.7), pitch: frandom(0.8,1.2));
		}
				
		A_SetPitch(pitch - 0.25);
		A_SetAngle(angle + (frandom(-0.1,0.1)));
				
		TSP_SpriteBumper bumper;
		
		bumper = new("TSP_SpriteBumper");
		bumper.fadein = 1;
		bumper.fadeout = 9;
		bumper.bump_amount = frandom(4.2,4.4);
		bumper.bump_angle = 50+frandom(-15.0,15.0);
		A_TSP_AddBumper(bumper);
		
		invoker.proton_mult += 0.05;
	}
}