/*
	The Space Pirate
	Caster
	
	Outlawdy Starswell
*/

Class TSP_Weapon_Caster : TSP_BaseWeapon
{
	action void A_TSP_FireCaster()
	{
		switch (random(0,2))
		{
			case 0:
				SpawnPlayerMissile("BFGBall", angle);
				break;
			case 1:
				SpawnPlayerMissile("Rocket", angle);
				break;
			case 2:
				SpawnPlayerMissile("PlasmaBall", angle+frandom(-5,5));
				SpawnPlayerMissile("PlasmaBall", angle+frandom(-5,5));
				SpawnPlayerMissile("PlasmaBall", angle+frandom(-5,5));
				SpawnPlayerMissile("PlasmaBall", angle+frandom(-5,5));
				SpawnPlayerMissile("PlasmaBall", angle+frandom(-5,5));
				break;
		}
	}
	
	States
	{
		Select:
			161G A 1 A_Raise();
			Wait;
		Deselect:
			161G A 1 A_TSP_Deselect();
			Wait;
		Ready:
			161G A 1
			{
				invoker.LookScale = 1.0;
				A_WeaponReady();
			}
			Loop;
		Fire:
			Goto Fire_ProtonCannon;
		
		Anim_Fire:
			TNT1 A 0
			{
				TSP_ViewRecoil recoil;
				
				recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.pitch = -0.2;
				recoil.roll = 0.1;
				recoil.roll_shake = 0.1;
				recoil.roll_speed = 50.0;
				A_TSP_AddRecoil(recoil);
				
				recoil = new("TSP_ViewRecoil");
				recoil.shake_amount = 0.1;
				recoil.fadeout = 4;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(8.37, 41.99);
			TNT1 A 1 A_WeaponOffset(16.75, 56.39);
			TNT1 A 1 A_WeaponOffset(16.41, 53.10);
			TNT1 A 1 A_WeaponOffset(14.74, 46.95);
			TNT1 A 1 A_WeaponOffset(10.44, 41.30);
			TNT1 A 1 A_WeaponOffset(6.81, 38.22);
			TNT1 A 1 A_WeaponOffset(4.65, 36.31);
			TNT1 A 1 A_WeaponOffset(3.22, 35.01);
			TNT1 A 1 A_WeaponOffset(2.22, 34.08);
			TNT1 A 1 A_WeaponOffset(1.49, 33.40);
			TNT1 A 1 A_WeaponOffset(0.96, 32.90);
			TNT1 A 1 A_WeaponOffset(0.57, 32.54);
			TNT1 A 1 A_WeaponOffset(0.30, 32.28);
			TNT1 A 1 A_WeaponOffset(0.13, 32.12);
			Stop;
	}
}