/*
	The Space Pirate
	Fists
	
	Punchody fistswell.
*/

const PSP_WEAPONANIM = 67;

Class TSP_Weapon_MelFists : TSP_BaseWeapon
{
	States
	{
		Select:
			111A A 1 A_Raise();
			Wait;
		Deselect:
			111A A 1 A_TSP_Deselect();
			Wait;
		Ready:
			111A A 1 A_TSP_WeaponReady();
			Loop;
		Fire:
			Goto PunchRight;
			
		PunchRight:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchRight");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			111F A 2;
			111F B 1;
			"----" A 0 A_TSP_Melee(10);
			111F C 6;
			111F C 6 A_TSP_AddNextState("PunchLeft");
			TNT1 A 2;
			Goto Ready;
		PunchLeft:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchLeft");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			111G A 2;
			111G B 1;
			"----" A 0 A_TSP_Melee(12);
			111G C 6;
			111G C 6 A_TSP_AddNextState("PunchOverheadRight");
			TNT1 A 2;
			Goto Ready;
		PunchOverheadRight:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_OverheadRight");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			111F D 3;
			111F E 1;
			"----" A 0 A_TSP_Melee(12);
			111F F 13;
			TNT1 A 2;
			Goto Ready;
			
		Anim_PunchRight:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = 0.2;
				recoil.yaw_shake = 0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = -0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(-14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(-30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(-19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(-20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(-22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(-21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(-18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(-9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(82.30, 95.33);
			Stop;
			
		Anim_PunchLeft:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = -0.2;
				recoil.yaw_shake = -0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = 0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(-125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(-120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(-11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(-10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(-46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(-82.30, 95.33);
			Stop;
			
		Anim_OverheadRight:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 4;
				recoil.fadeout = 13;
				recoil.yaw = 1.0;
				recoil.yaw_shake = 0.1;
				recoil.yaw_speed = 50.0;
				recoil.roll = -1;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(321.31, 83.37);
			TNT1 A 1 A_WeaponOffset(252.61, 35.45);
			TNT1 A 1 A_WeaponOffset(114.86, 32.53);
			TNT1 A 1 A_WeaponOffset(25.11, 32.00);
			TNT1 A 1 A_WeaponOffset(-4.23, 32.31);
			TNT1 A 1 A_WeaponOffset(-7.65, 32.54);
			TNT1 A 1 A_WeaponOffset(-19.18, 32.70);
			TNT1 A 1 A_WeaponOffset(-27.58, 33.10);
			TNT1 A 1 A_WeaponOffset(-36.49, 34.00);
			TNT1 A 1 A_WeaponOffset(-49.98, 36.65);
			TNT1 A 1 A_WeaponOffset(-71.04, 45.18);
			TNT1 A 1 A_WeaponOffset(-102.87, 58.64);
			TNT1 A 1 A_WeaponOffset(-138.96, 77.36);
			TNT1 A 1 A_WeaponOffset(-167.82, 102.14);
			TNT1 A 1 A_WeaponOffset(-189.05, 134.82);
			TNT1 A 1 A_WeaponOffset(-205.18, 180.45);
			Stop;
	}
}