/*
	The Space Pirate
	Fists
	
	Punchody fistswell.
*/

const PSP_OFFHAND = 69;

const PSP_LEFTHAND = 69;
const PSP_RIGHTHAND = 70;

Class TSP_Weapon_MelFists : TSP_BaseWeapon
{
	States
	{
		Select:
			111A A 1 A_Raise();
			Wait;
		Deselect:
			111A A 1 A_TSP_Deselect();
			Wait;
		Ready:
			111A A 1 A_TSP_WeaponReady();
			Loop;
		Fire:
			Goto PunchRight;
			
		PunchRight:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchRight");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			111F A 2;
			111F B 1;
			"----" A 0 A_TSP_Melee(10);
			111F C 2;
			"----" A 0 A_TSP_SetNextState("PunchLeft");
			111F C 10;
			Goto Ready;
		PunchRight_GoAway:
			111F C 0
			{
				A_OverlayFlags(OverlayID(), PSPF_ADDWEAPON, false);
				A_OverlayOffset(OverlayID(), 0, 32, WOF_ADD);
			}
			"----" A 1 A_OverlayOffset(OverlayID(), 32, 8, WOF_ADD);
			"----" A 1 A_OverlayOffset(OverlayID(), 64, 32, WOF_ADD);
			"----" A 1 A_OverlayOffset(OverlayID(), 144, 96, WOF_ADD);
			Stop;
			
		PunchLeft:
			"----" A 0
			{
				A_Overlay(PSP_OFFHAND, "PunchRight_GoAway");
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchLeft");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			111G A 2;
			111G B 1;
			"----" A 0 A_TSP_Melee(12);
			111G C 2;
			"----" A 0 A_TSP_SetNextState("PunchOverheadRight");
			111G C 10;
			Goto Ready;
		PunchLeft_GoAway:
			111G C 0
			{
				A_OverlayFlags(OverlayID(), PSPF_ADDWEAPON, false);
				A_OverlayOffset(OverlayID(), 0, 32, WOF_ADD);
			}
			"----" A 1 A_OverlayOffset(OverlayID(), -32, 8, WOF_ADD);
			"----" A 1 A_OverlayOffset(OverlayID(), -64, 32, WOF_ADD);
			"----" A 1 A_OverlayOffset(OverlayID(), -144, 96, WOF_ADD);
			Stop;
			
		PunchOverheadRight:
			"----" A 0
			{
				A_Overlay(PSP_OFFHAND, "PunchLeft_GoAway");
				A_Overlay(PSP_WEAPONANIM, "Anim_OverheadRight");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			111F D 2;
			111F E 1;
			"----" A 0 A_TSP_Melee(12);
			111F F 3;
			"----" A 0 A_TSP_SetNextState("PunchUppercut");
			111F F 10;
			TNT1 A 2;
			Goto Ready;
			
		PunchUppercut:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_Uppercut");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			111U A 2;
			111U A 1;
			"----" A 0 
			{
				A_TSP_Melee(40);
				let effect = TSP_HitEffect_Thrust.Create(invoker.owner, (3,0,9));
				A_TSP_ApplyToVictims(effect);	
			}
			111U A 13;
			TNT1 A 2;
			Goto Ready;
			
		Anim_PunchRight:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = 0.2;
				recoil.yaw_shake = 0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = -0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(-14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(-30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(-19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(-20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(-22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(-21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(-18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(-9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(82.30, 95.33);
			Stop;
			
		Anim_PunchLeft:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = -0.2;
				recoil.yaw_shake = -0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = 0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(-125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(-120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(-11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(-10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(-46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(-82.30, 95.33);
			Stop;
			
		Anim_OverheadRight:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 4;
				recoil.fadeout = 13;
				recoil.yaw = 1.0;
				recoil.yaw_shake = 0.1;
				recoil.yaw_speed = 50.0;
				recoil.roll = -1;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(321.31, 83.37);
			TNT1 A 1 A_WeaponOffset(252.61, 35.45);
			TNT1 A 1 A_WeaponOffset(114.86, 32.53);
			TNT1 A 1 A_WeaponOffset(25.11, 32.00);
			TNT1 A 1 A_WeaponOffset(-4.23, 32.31);
			TNT1 A 1 A_WeaponOffset(-7.65, 32.54);
			TNT1 A 1 A_WeaponOffset(-19.18, 32.70);
			TNT1 A 1 A_WeaponOffset(-27.58, 33.10);
			TNT1 A 1 A_WeaponOffset(-36.49, 34.00);
			TNT1 A 1 A_WeaponOffset(-49.98, 36.65);
			TNT1 A 1 A_WeaponOffset(-71.04, 45.18);
			TNT1 A 1 A_WeaponOffset(-102.87, 58.64);
			TNT1 A 1 A_WeaponOffset(-138.96, 77.36);
			TNT1 A 1 A_WeaponOffset(-167.82, 102.14);
			TNT1 A 1 A_WeaponOffset(-189.05, 134.82);
			TNT1 A 1 A_WeaponOffset(-205.18, 180.45);
			Stop;
			
		Anim_Uppercut:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 4;
				recoil.fadeout = 8;
				recoil.pitch = -5.0;
				recoil.yaw = -0.4;
				recoil.yaw_shake = 0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = -1;
				recoil.yaw_shake = 0.15;
				recoil.yaw_speed = 55.0;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(-29.00, 230.00);
			TNT1 A 1 A_WeaponOffset(-15.59, 113.47);
			TNT1 A 1 A_WeaponOffset(-12.14, 57.68);
			TNT1 A 1 A_WeaponOffset(-11.40, 37.57);
			TNT1 A 1 A_WeaponOffset(-11.35, 32.00);
			TNT1 A 1 A_WeaponOffset(-11.32, 31.21);
			TNT1 A 1 A_WeaponOffset(-11.32, 30.30);
			TNT1 A 1 A_WeaponOffset(-11.37, 29.52);
			TNT1 A 1 A_WeaponOffset(-11.50, 29.01);
			TNT1 A 1 A_WeaponOffset(-11.78, 28.55);
			TNT1 A 1 A_WeaponOffset(-12.33, 30.23);
			TNT1 A 1 A_WeaponOffset(-13.39, 37.33);
			TNT1 A 1 A_WeaponOffset(-15.43, 52.92);
			TNT1 A 1 A_WeaponOffset(-18.66, 84.98);
			Stop;
	}
}