/*
	The Space Pirate
	Medusa
	
	Nunody Chuckswell
*/

Class TSP_Weapon_Medusa : TSP_BaseWeapon
{
	States
	{
		Select:
			W030 A 1 A_Raise();
			Wait;
		Deselect:
			W030 A 1 A_TSP_Deselect();
			Wait;
		Ready:
			W030 A 1 A_WeaponReady();
			Loop;
		Fire:
			W030 B 1 A_WeaponOffset(-192, 64);
			W030 B 2 A_WeaponOffset(-128, 32);
			W030 C 2
			{
				A_TSP_Melee(10);
				A_WeaponOffset(0, 32);
			}
			W030 C 2 A_WeaponOffset(128, 32);
			W030 C 1 A_WeaponOffset(192, 64);
			"----" A 0 A_Refire("Refire");
			Goto Ready;
		Refire:
			W030 D 1 A_WeaponOffset(192, 64);
			W030 D 2 A_WeaponOffset(128, 32);
			W030 E 2
			{
				A_TSP_Melee(10);
				A_WeaponOffset(0, 32);
			}
			W030 E 2 A_WeaponOffset(-128, 32);
			W030 E 1 A_WeaponOffset(-192, 64);
			"----" A 0 A_Refire("Fire");
			Goto Ready;
	}
}