/*
	The Space Pirate
	Darling Nikki
	
	Gunody pistwell.
*/

Class TSP_Weapon_DarlingNikki : TSP_BaseWeapon
{
	States
	{
		Select:
			122G A 1 A_Raise();
			Wait;
		Deselect:
			122G A 1 A_TSP_Deselect();
			Wait;
		Ready:
			122G A 1 A_TSP_WeaponReady();
			Loop;
		Fire:
			"----" A 0 A_Overlay(PSP_WEAPONANIM, "Anim_Fire");
			122G B 2
			{
				A_TSP_FireBullets(3, 2, 1, 10);
				A_StartSound("nikki/default/fire", CHAN_WEAPON);
				A_GunFlash("Flash");
			}
			122G C 2;
			"----" A 0 A_TSP_SetNextState("Fire");
			122G DE 2;
			Goto Ready;
			
		Flash:
			122F A 2 BRIGHT
			{
				A_OverlayFlags(OverlayID(), PSPF_RENDERSTYLE|PSPF_ADDWEAPON, true);
				A_OverlayRenderstyle(OverlayID(), STYLE_Add);
			}
			Stop;
			
		Anim_Fire:
			TNT1 A 0
			{
				TSP_ViewRecoil recoil;
				
				recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.pitch = -0.2;
				recoil.roll = 0.1;
				recoil.roll_shake = 0.1;
				recoil.roll_speed = 50.0;
				A_TSP_AddRecoil(recoil);
				
				recoil = new("TSP_ViewRecoil");
				recoil.shake_amount = 0.1;
				recoil.fadeout = 4;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(8.37, 41.99);
			TNT1 A 1 A_WeaponOffset(16.75, 56.39);
			TNT1 A 1 A_WeaponOffset(16.41, 53.10);
			TNT1 A 1 A_WeaponOffset(14.74, 46.95);
			TNT1 A 1 A_WeaponOffset(10.44, 41.30);
			TNT1 A 1 A_WeaponOffset(6.81, 38.22);
			TNT1 A 1 A_WeaponOffset(4.65, 36.31);
			TNT1 A 1 A_WeaponOffset(3.22, 35.01);
			TNT1 A 1 A_WeaponOffset(2.22, 34.08);
			TNT1 A 1 A_WeaponOffset(1.49, 33.40);
			TNT1 A 1 A_WeaponOffset(0.96, 32.90);
			TNT1 A 1 A_WeaponOffset(0.57, 32.54);
			TNT1 A 1 A_WeaponOffset(0.30, 32.28);
			TNT1 A 1 A_WeaponOffset(0.13, 32.12);
			Stop;
	}
}