/*
	The Space Pirate
	Darling Nikki
	
	Gunody pistwell.
*/

Class TSP_Weapon_DarlingNikki : TSP_BaseWeapon
{
	States
	{
		Select:
			122G A 1 A_Raise();
			Wait;
		Deselect:
			122G A 1 A_TSP_Deselect();
			Wait;
		Ready:
			122G A 1 A_TSP_WeaponReady(WRF_ALLOWZOOM);
			Loop;
		Fire:
			"----" A 0 A_Overlay(PSP_WEAPONANIM, "Anim_Fire");
			122G B 2
			{
				A_TSP_FireBullets(3, 2, 1, 10);
				A_StartSound("nikki/default/fire", CHAN_WEAPON);
				A_GunFlash("Flash");
			}
			122G C 2;
			"----" A 0 A_TSP_SetNextState("Fire");
			122G DE 2;
			Goto Ready;
		
		AltReady:
			122A A 1 A_TSP_WeaponReady(WRF_ALLOWZOOM);
			Loop;
		AltFire:
			"----" A 0 A_Overlay(PSP_WEAPONANIM, "Anim_AltFire");
			122A B 2
			{
				A_TSP_FireBullets(3, 2, 1, 10);
				A_StartSound("nikki/spitfire/fire", CHAN_WEAPON);
				A_GunFlash("AltFlash");
			}
			122A C 1;
			"----" A 0 A_TSP_SetNextState("AltFire", held_buttons: BT_ATTACK);
			122A C 1;
			Goto AltReady;
		
		NormalToAlt:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_ModSwitch");
				A_StartSound("nikki/spitfire/aim01", 12);
				A_TSP_ZoomFactor(0.95);
			}
			122G A 2;
			122A D 1;
			122A A 2;
			Goto AltReady;
		AltToNormal:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_ModSwitch");
				A_StartSound("nikki/spitfire/aim01", 12);
				A_TSP_ZoomFactor(1.0);
			}
			122A A 2;
			122A D 1;
			122G A 2;
			Goto Ready;
			
		Zoom:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_Melee");
			}
			122G A 8;
			"----" A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 3;
				recoil.fadeout = 8;
				recoil.yaw = -0.2;
				recoil.pitch = 0.1;
				recoil.yaw_shake = 0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = -0.2;
				A_TSP_AddRecoil(recoil);
			}
			122M A 2;
			"----" A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 12;
				recoil.pitch = 0.3;
				recoil.roll = -0.2;
				A_TSP_AddRecoil(recoil);
				
				A_TSP_Melee(10);
				let effect = TSP_HitEffect_Thrust.Create(invoker.owner, (7,0,1));
				A_TSP_ApplyToVictims(effect);
				//let effect = TSP_HitEffect_Stun.Create(invoker.owner, (3,0,1));
				//A_TSP_ApplyToVictims(effect);
			}
			122M A 4;
			122M A 6 A_TSP_SetNextState("QuickMelee", BT_ATTACK, BT_ZOOM);
			Goto Ready;
			
		Flash:
			122F A 1 BRIGHT
			{
				A_OverlayFlags(OverlayID(), PSPF_RENDERSTYLE|PSPF_ADDWEAPON, true);
				A_OverlayRenderstyle(OverlayID(), STYLE_Add);
			}
			Stop;
		AltFlash:
			122F B 1 BRIGHT
			{
				A_OverlayFlags(OverlayID(), PSPF_RENDERSTYLE|PSPF_ADDWEAPON, true);
				A_OverlayRenderstyle(OverlayID(), STYLE_Add);
				invoker.owner.player.FindPSprite(OverlayID()).frame = random(1,4);
			}
			Stop;
			
		Anim_Fire:
			TNT1 A 0
			{
				TSP_ViewRecoil recoil;
				
				recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.pitch = -0.2;
				recoil.roll = 0.1;
				recoil.roll_shake = 0.1;
				recoil.roll_speed = 50.0;
				A_TSP_AddRecoil(recoil);
				
				recoil = new("TSP_ViewRecoil");
				recoil.shake_amount = 0.1;
				recoil.fadeout = 4;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(8.37, 41.99);
			TNT1 A 1 A_WeaponOffset(16.75, 56.39);
			TNT1 A 1 A_WeaponOffset(16.41, 53.10);
			TNT1 A 1 A_WeaponOffset(14.74, 46.95);
			TNT1 A 1 A_WeaponOffset(10.44, 41.30);
			TNT1 A 1 A_WeaponOffset(6.81, 38.22);
			TNT1 A 1 A_WeaponOffset(4.65, 36.31);
			TNT1 A 1 A_WeaponOffset(3.22, 35.01);
			TNT1 A 1 A_WeaponOffset(2.22, 34.08);
			TNT1 A 1 A_WeaponOffset(1.49, 33.40);
			TNT1 A 1 A_WeaponOffset(0.96, 32.90);
			TNT1 A 1 A_WeaponOffset(0.57, 32.54);
			TNT1 A 1 A_WeaponOffset(0.30, 32.28);
			TNT1 A 1 A_WeaponOffset(0.13, 32.12);
			Stop;
		
		Anim_AltFire:
			TNT1 A 0
			{
				TSP_ViewRecoil recoil;
				
				recoil = new("TSP_ViewRecoil");
				recoil.fadein = 1;
				recoil.fadeout = 7;
				recoil.pitch = -0.15;
				recoil.yaw = frandom(-0.1,0.1);
				recoil.roll = frandom(-0.2,0.2);
				recoil.roll_shake = 0.2;
				recoil.roll_speed = 50.0;
				A_TSP_AddRecoil(recoil);
				
				recoil = new("TSP_ViewRecoil");
				recoil.shake_amount = 0.15;
				recoil.fadeout = 4;
				A_TSP_AddRecoil(recoil);
				
				TSP_SpriteBumper bumper;
				
				bumper = new("TSP_SpriteBumper");
				bumper.fadein = 1;
				bumper.fadeout = 9;
				bumper.bump_amount = frandom(2.0,6.0);
				bumper.bump_angle = 90+frandom(-25.0,25.0);
				A_TSP_AddBumper(bumper);
			}
			Stop;
			
		Anim_ModSwitch:
			TNT1 A 1 A_WeaponOffset(0.00, 32.00);
			TNT1 A 1 A_WeaponOffset(0.00, 49.12);
			TNT1 A 1 A_WeaponOffset(-0.88, 51.71);
			TNT1 A 1 A_WeaponOffset(-1.60, 51.35);
			TNT1 A 1 A_WeaponOffset(-1.20, 50.17);
			TNT1 A 1 A_WeaponOffset(0.05, 47.96);
			TNT1 A 1 A_WeaponOffset(1.23, 44.68);
			TNT1 A 1 A_WeaponOffset(0.84, 40.83);
			TNT1 A 1 A_WeaponOffset(0.00, 37.33);
			TNT1 A 1 A_WeaponOffset(0.00, 34.75);
			TNT1 A 1 A_WeaponOffset(0.00, 33.11);
			TNT1 A 1 A_WeaponOffset(0.00, 32.25);
			TNT1 A 1 A_WeaponOffset(0.00, 32.00);
			TNT1 A 1 A_WeaponOffset(0.00, 32.00);
			Stop;
			
		Anim_Melee:
			TNT1 A 1 A_WeaponOffset(0.00, 32.00);
			TNT1 A 1 A_WeaponOffset(47.25, 94.50);
			TNT1 A 1 A_WeaponOffset(128.00, 157.00);
			TNT1 A 1 A_WeaponOffset(163.00, -248.00);
			TNT1 A 1 A_WeaponOffset(153.45, -243.26);
			TNT1 A 1 A_WeaponOffset(128.21, -228.15);
			TNT1 A 1 A_WeaponOffset(92.42, -201.38);
			TNT1 A 1 A_WeaponOffset(51.20, -161.64);
			TNT1 A 1 A_WeaponOffset(9.68, -107.61);
			TNT1 A 1 A_WeaponOffset(-27.00, -38.00);
			TNT1 A 1 A_WeaponOffset(-54.80, 46.13);
			TNT1 A 1 A_WeaponOffset(-74.02, 134.16);
			TNT1 A 1 A_WeaponOffset(-86.04, 213.12);
			TNT1 A 1 A_WeaponOffset(-92.24, 270.02);
			TNT1 A 1 A_WeaponOffset(-94.00, 291.87);
			TNT1 A 1 A_WeaponOffset(-94.00, 291.87);
			TNT1 A 1 A_WeaponOffset(-94.00, 291.87);
			Stop;
	}
}