/*
	The Space Pirate
	Shiva Gauntlets
	
	Robotody Hitswell
*/

Class TSP_Weapon_ShivaGauntlets : TSP_BaseWeapon
{
	States
	{
		Select:
			151G A 1 A_Raise();
			Wait;
		Deselect:
			151G A 1 A_TSP_Deselect();
			Wait;
		Ready:
			151G A 1 A_TSP_WeaponReady();
			Loop;
		Fire:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchRight");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			151G B 5;
			"----" A 0 A_TSP_Melee(40);
			151G B 10;
			"----" A 0 A_TSP_SetNextState("Fire2");
			151G B 10;
			Goto Ready;
		Fire2:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchLeft");
				A_StartSound("melee/basic/normal/miss", 12);
			}
			151G C 5;
			"----" A 0 A_TSP_Melee(40);
			151G C 10;
			"----" A 0 A_TSP_SetNextState("Fire");
			151G C 10;
			Goto Ready;
			
		Anim_PunchRight:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = 0.2;
				recoil.yaw_shake = 0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = -0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(-14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(-30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(-19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(-20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(-22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(-21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(-18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(-9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(82.30, 95.33);
			Stop;
			
		Anim_PunchLeft:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = -0.2;
				recoil.yaw_shake = -0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = 0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(-125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(-120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(-11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(-10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(-46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(-82.30, 95.33);
			Stop;
	}
}