/*
	The Space Pirate
	Shiva Gauntlets
	
	Robotody Hitswell
*/

Class TSP_ShivaGauntlet_RokketoPawnch : Actor
{
	bool retracting;
	int hitDelay;
	double backSpeed;
	
	Default
	{
		Projectile;
		Speed 45;
		Damage (50);
		+ALLOWBOUNCEONACTORS
		+BOUNCEONACTORS
		+BOUNCEONWALLS
		+BOUNCEONFLOORS
		+BOUNCEONCEILINGS
		+BRIGHT
	}
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		A_StartSound("shiva/rokket/fly", CHAN_VOICE, CHANF_LOOPING);
	}
	
	override void Tick()
	{
		super.Tick();
		if ( retracting )
		{
			if ( hitDelay > 0 )
			{
				hitDelay--;
				return;
			}
			Vector3 diff = (target.pos - pos);
			vel = (vel.Unit() + diff.Unit()).Unit() * backSpeed;
			backSpeed = min(speed, backSpeed+3);
			if ( diff.Length() <= speed )
			{
				A_StopSound(CHAN_VOICE);
				target.A_StartSound("shiva/return", CHAN_WEAPON, CHANF_OVERLAP);
				Destroy();
			}
		}
	}
	
	override int SpecialBounceHit (Actor bounceMobj, Line bounceLine, readonly<SecPlane> bouncePlane, bool is3DFloor)
	{
		if ( !retracting )
		{
			retracting = true;
			bNOCLIP = true;
			hitDelay = 3;
			vel = (0,0,0.25);
			A_Explode(144, 128, 0);
			A_StartSound("shiva/impact/wall", CHAN_BODY);
			if ( bounceMobj )
			{
				bounceMobj.A_StartSound("shiva/impact/rocketpunch", CHAN_BODY);
			}
			Spawn("TSP_RocketPunchImpact", pos);
			backSpeed = 1/35.;
		}
		return -1;
	}	
	
	States
	{
		Spawn:
			MISL A -1;
			Stop;
	}
}

Class TSP_Weapon_ShivaGauntlets : TSP_BaseWeapon
{
	Default
	{
		+TSP_BaseWeapon.HOLDFORMOD
	}
	
	TSP_ShivaGauntlet_RokketoPawnch rokketo;
	
	States
	{
		Select:
			151G A 1 A_Raise();
			Wait;
		Deselect:
			151G A 1 A_TSP_Deselect();
			Wait;
		Ready:
			151G A 1 A_TSP_WeaponReady();
			Loop;
		Fire:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchRight");
				A_StartSound("shiva/swing", 0);
			}
			151G B 5;
			"----" A 0
			{
				A_TSP_Melee(40);
				let effect = TSP_HitEffect_Cleave.Create(invoker.owner, 192, 20);
				A_TSP_ApplyToVictims(effect);	
			}
			151G B 10;
			"----" A 0 A_TSP_SetNextState("Fire2");
			151G B 10;
			Goto Ready;
		Fire2:
			"----" A 0
			{
				A_Overlay(PSP_WEAPONANIM, "Anim_PunchLeft");
				A_StartSound("shiva/swing", 0);
			}
			151G C 5;
			"----" A 0
			{
				A_TSP_Melee(40);
				let effect = TSP_HitEffect_Cleave.Create(invoker.owner, 192, 20);
				A_TSP_ApplyToVictims(effect);	
			}
			151G C 10;
			"----" A 0 A_TSP_SetNextState("Fire");
			151G C 10;
			Goto Ready;
		
		AltReady:
			151G B 1 A_TSP_WeaponReady(WRF_ALLOWZOOM);
			Loop;
		AltFire:
			151G B 12
			{
				if ( invoker.rokketo )
				{
					return resolveState(null);
				}
				A_Overlay(PSP_WEAPONANIM, "Anim_RocketFire");
				invoker.rokketo = TSP_ShivaGauntlet_RokketoPawnch(A_FireProjectile("TSP_ShivaGauntlet_RokketoPawnch"));
				A_StartSound("shiva/launch", CHAN_WEAPON, flags: CHANF_OVERLAP);
				A_SetPitch(pitch - 1.8);
				A_SetAngle(angle + (frandom(-0.3,0.3)));
				return resolveState(null);
			}
			151G B 1;
			Goto AltReady;
		
		NormalToAlt:
			151G A 2 A_StartSound("shiva/launch/ready", 12);
			Goto AltReady;
		AltToNormal:
			151G A 2 A_StartSound("shiva/launch/unready", 12);
			Goto Ready;
			
		Anim_PunchRight:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = 0.2;
				recoil.yaw_shake = 0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = -0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(-14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(-30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(-19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(-20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(-22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(-21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(-18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(-9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(82.30, 95.33);
			Stop;
			
		Anim_PunchLeft:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 2;
				recoil.fadeout = 8;
				recoil.yaw = -0.2;
				recoil.yaw_shake = -0.2;
				recoil.yaw_speed = 50.0;
				recoil.roll = 0.5;
				A_TSP_AddRecoil(recoil);
			}
			TNT1 A 1 A_WeaponOffset(-125.00, 149.00);
			TNT1 A 1 A_WeaponOffset(-120.15, 90.16);
			TNT1 A 1 A_WeaponOffset(-11.39, 32.00);
			TNT1 A 1 A_WeaponOffset(14.54, 32.31);
			TNT1 A 1 A_WeaponOffset(30.42, 33.37);
			TNT1 A 1 A_WeaponOffset(19.83, 34.95);
			TNT1 A 1 A_WeaponOffset(20.91, 36.87);
			TNT1 A 1 A_WeaponOffset(22.00, 39.00);
			TNT1 A 1 A_WeaponOffset(21.93, 41.60);
			TNT1 A 1 A_WeaponOffset(18.57, 45.47);
			TNT1 A 1 A_WeaponOffset(9.60, 51.30);
			TNT1 A 1 A_WeaponOffset(-10.13, 59.99);
			TNT1 A 1 A_WeaponOffset(-46.52, 73.24);
			TNT1 A 1 A_WeaponOffset(-82.30, 95.33);
			Stop;
			
		Anim_RocketFire:
			TNT1 A 0
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.fadein = 1;
				recoil.fadeout = 25;
				recoil.pitch = -2.2;
				recoil.pitch_shake = 0.05;
				recoil.pitch_speed = 35.0;
				recoil.yaw = -0.2;
				recoil.yaw_shake = -0.1;
				recoil.yaw_speed = 50.0;
				recoil.roll = 0.5;
				recoil.roll_shake = -1.0;
				recoil.roll_speed = 35.0;
				A_TSP_AddRecoil(recoil);
			}
			Stop;
	}
}