Class MelMeleeTest : TSP_Mel_BaseWeapon
{
	string fireSound;
	
	enum ETSPComboInputType
	{
		CIT_ATTACK,
		CIT_ALTATTACK,
	};
	
	property FireSound : fireSound;
	
	Default
	{
	}
	
	action void A_TSP_ComboInput(int inputType, bool noHold, State state)
	{
		bool doJump = false;
		
		switch ( inputType )
		{
			case CIT_ATTACK:
				doJump = invoker.owner.player.cmd.buttons & BT_ATTACK && (noHold ? !(invoker.owner.player.oldbuttons & BT_ATTACK) : true);
				break;
			case CIT_ALTATTACK:
				doJump = invoker.owner.player.cmd.buttons & BT_ALTATTACK && (noHold ? !(invoker.owner.player.oldbuttons & BT_ALTATTACK) : true);
				break;
		}
		
		if ( doJump )
		{
			invoker.owner.player.SetPSprite(PSP_WEAPON, state);
		}
	}
	
	States
	{
		Select:
			TNT1 A 0
			{
				A_Raise(32);
				A_TSP_AllowZoom(false);
			}
			111U ABC 2;
			Loop;
		Deselect:
			TNT1 A 0
			{
				A_Raise(32);
				A_TSP_AllowZoom(false);
			}
			Loop;
		
		Ready:
			TNT1 A 0 A_JumpIfInventory("MeleePressed",1,"SPMelee");
			TNT1 A 0 A_JumpIfInventory("TraitPressed",1,"SPTrait");
			1111 A 1
			{
				A_TSP_ComboInput(CIT_ATTACK, true, resolveState("Punch1"));
				A_TSP_ComboInput(CIT_ALTATTACK, true, resolveState("Kick1"));
			}
			"####" A 0 A_TSP_GotoReadyState;
			Loop;
			
		Punch1:
			1111 D 3
			{
				A_StartSound("basicmelee/miss", CHAN_5);
				Console.Printf("Punch 1");
			}
			1111 AAAAAAAAAAAAAAAAAAAA 1
			{
				A_TSP_ComboInput(CIT_ATTACK, true, resolveState("Punch2"));
				A_TSP_ComboInput(CIT_ALTATTACK, true, resolveState("Kick2"));
			}
			Goto Ready;
		Punch2:
			1111 D 3
			{
				A_StartSound("basicmelee/miss", CHAN_5);
				Console.Printf("Punch 2");
			}
			1111 AAAAAAAAAAAAAAAAAAAA 1
			{
				A_TSP_ComboInput(CIT_ATTACK, true, resolveState("Punch3"));
				A_TSP_ComboInput(CIT_ALTATTACK, true, resolveState("Kick3"));
			}
			Goto Ready;
		Punch3:
			1111 D 1
			{
				A_StartSound("basicmelee/miss", CHAN_5);
				Console.Printf("Punch 3");
			}
			"----" AAAAAAAAAAAAAAAAAAAA 1
			{
				A_WeaponOffset(frandom(-1,1), frandom(31,33), WOF_INTERPOLATE);
			}
			Goto Ready;
			
		Kick1:
			111L D 3
			{
				A_StartSound("basicmelee/miss", CHAN_5);
				Console.Printf("Kick 1");
			}
			111L AAAAAAAAAAAAAAAAAAAA 1
			{
				A_TSP_ComboInput(CIT_ATTACK, true, resolveState("Punch2"));
				A_TSP_ComboInput(CIT_ALTATTACK, true, resolveState("Kick2"));
			}
			Goto Ready;
		Kick2:
			111L D 3
			{
				A_StartSound("basicmelee/miss", CHAN_5);
				Console.Printf("Kick 2");
			}
			111L AAAAAAAAAAAAAAAAAAAA 1
			{
				A_TSP_ComboInput(CIT_ATTACK, true, resolveState("Punch3"));
				A_TSP_ComboInput(CIT_ALTATTACK, true, resolveState("Kick3"));
			}
			Goto Ready;
		Kick3:
			111L D 1
			{
				A_StartSound("basicmelee/miss", CHAN_5);
				Console.Printf("Kick 3");
			}
			"----" AAAAAAAAAAAAAAAAAAAA 1
			{
				A_WeaponOffset(frandom(-1,1), frandom(31,33), WOF_INTERPOLATE);
			}
			Goto Ready;
	}
}