Extend Class TSP_EpisodeMenu
{
	void BountyHuntersInit()
	{
		let header = new("TSP_MenuHeader");
		header.text = "Bounty Hunters";
		AddItem(header);
		
		int x = 320;
		int y = 32;
		
		for ( int i = 0; i < LevelInfo.GetLevelInfoCount(); i++ )
		{
			let info = LevelInfo.GetLevelInfo(i);
			
			let button = new("TSP_MenuButton");
			button.Init();
			button.text = info.LookupLevelName();
			button.pos = (x, y);
			button.size = (256, 24);
			y += 24;
			if ( y >= 720 )
			{
				x += 256;
				y = 32;
			}
			
			let menuaction = new("TSP_MenuAction");
			menuaction.type = TSP_MenuAction.RETURN_VALUE;
			menuaction.value = info.MapName;
			button.menuaction = menuaction;
			
			AddItem(button);
		}
	}
}