Extend Class TSP_PlayerPawn_ZSCBase
{
	bool pp_switchingmod;
	TSP_Weapon_Core pp_nextModSwitch;
	int pp_moddelay;
	
	double pp_punchWarp;
	double tsp_fb_zoom;
	double tsp_fb_zoomlerp;
	
	double view_zoom;
	double view_zoomLerp;
	
	int hit_freeze;
	int hit_freezeMax;
	
	Array<int> input_buffer;
	
	override void FireWeapon (State stat)
	{
		let psprite_weapon = player.FindPSprite(PSP_WEAPON);
		psprite_weapon.x = 0;
		psprite_weapon.y = 32;
		super.FireWeapon(stat);
	}
	
	override void FireWeaponAlt (State stat)
	{
		return;
		let tsp_weap = TSP_BaseWeapon(player.ReadyWeapon);
		let stat = tsp_weap.FindState("AltFire");
		
		FireWeapon(stat);
		return;
	}
	
	const INPUTBUFFER_SIZE = 8;
	
	bool CheckInputBuffer (int value)
	{
		for ( int i = 0; i < input_buffer.size(); i++ )
		{
			if ( input_buffer[i] & value == value )
			{
				return true;
			}
		}
		return false;
	}
	
	bool CheckInputBufferHeld (int value, int max)
	{
		int counter = 0;
		for ( int i = 0; i < input_buffer.size(); i++ )
		{
			if ( input_buffer[i] & value == value )
			{
				counter += 1;
				if ( counter >= max )
				{
					return true;
				}
				continue;
			}
			if ( counter > 0 )
			{
				return false;
			}
		}
		return false;
	}
	
	bool TSP_TryNextMove()
	{
		let tsp_weap = TSP_BaseWeapon(player.ReadyWeapon);
		
		if ( !tsp_weap ) return false;
		
		if ( tsp_weap.nextmoves.size() <= 0 ) return false;
		
		for ( int i = 0; i < tsp_weap.nextmoves.size(); i++ )
		{
			int buttons = tsp_weap.nextmoves[i].buttons;
			int held_buttons = tsp_weap.nextmoves[i].held_buttons;
			
			if ( buttons != 0 )
			{
				if ( !CheckInputBuffer(player.buttons & buttons) )
				{
					continue;
				}
				if ( CheckInputBufferHeld(player.oldbuttons & buttons, 4) )
				{
					continue;
				}
			}
			
			if ( held_buttons != 0 )
			{
				if ( !((player.cmd.buttons & held_buttons) == held_buttons) || !((player.oldbuttons & held_buttons) == held_buttons) )
				{
					continue;
				}
			}
			
			FireWeapon(tsp_weap.nextmoves[i].statetarget);
			tsp_weap.nextmoves.Clear();
			return true;
		}
		
		return false;
	}
	
	void SetHitFreeze (int amount)
	{
		hit_freezeMax = amount;
		hit_freeze = amount;
	}
	
	override void TickPSprites()
	{
		if ( hit_freeze > 0 )
		{
			hit_freeze -= 1;
			return;
		}
		let player = self.player;
		let pspr = player.psprites;
		while (pspr)
		{
			// Destroy the psprite if it's from a weapon that isn't currently selected by the player
			// or if it's from an inventory item that the player no longer owns. 
			if ((pspr.Caller == null ||
				(pspr.Caller is "Inventory" && Inventory(pspr.Caller).Owner != pspr.Owner.mo) ||
				(pspr.Caller is "Weapon" && pspr.Caller != pspr.Owner.ReadyWeapon)))
			{
				pspr.Destroy();
			}
			else
			{
				pspr.Tick();
			}
			
			pspr = pspr.Next;
		}
		
		let psprite_weapon = player.FindPSprite(PSP_WEAPON);
		let tsp_weap = TSP_BaseWeapon(player.ReadyWeapon);
		
		if ( !psprite_weapon || !tsp_weap ) return;
		
		// [Py] If we're in the select state, it's free real estate
		if ( InStateSequence(psprite_weapon.CurState, player.ReadyWeapon.FindState("Select")) )
		{
			player.WeaponState = player.WeaponState | (WF_WEAPONREADY | WF_WEAPONREADYALT);
		}

		if ((health > 0) || (player.ReadyWeapon != null && !player.ReadyWeapon.bNoDeathInput))
		{
			if (player.ReadyWeapon == null)
			{
				if (player.PendingWeapon != WP_NOCHANGE)
					player.mo.BringUpWeapon();
			}
			else
			{
				CheckWeaponChange();
				TSP_CheckWeaponFire();
				/*if ( player.WeaponState & (WF_WEAPONREADY | WF_WEAPONREADYALT))
				{
					//CheckWeaponFire();
				}*/
				// Check custom buttons
				CheckWeaponButtons();
			}
		}
	}
	
	// this weapon chode
	
	ui void TSP_DrawPlayerDebug()
	{
		Font fnt = "smallfont";
		screen.DrawText(fnt, Font.CR_UNTRANSLATED, 0, 0,
			"Slide CD: "..tsp_slideCooldown.."\nOn Ground: "..player.onground,
			DTA_VirtualWidth, 320, DTA_VirtualHeight, 240);
	}
	
	void TSP_CheckWeaponFire()
	{
		let player = self.player;
		let weapon = player.ReadyWeapon;
		
		input_buffer.Push(player.cmd.buttons);
		while ( input_buffer.size() > INPUTBUFFER_SIZE )
		{
			input_buffer.Delete(0);
		}

		if (weapon == NULL)
			return;
		
		let tsp_weap = TSP_BaseWeapon(weapon);
		if ( !tsp_weap )
		{
			CheckWeaponFire();
			return;
		}
		
		if ( player.WeaponState & WF_WEAPONREADY )
		{
			if ( tsp_weap.bHoldForMod )
			{
				if ( player.cmd.buttons & BT_ALTATTACK )
				{
					if ( tsp_weap.SetAltActive(true) )
					{
						player.SetPSprite(PSP_WEAPON, tsp_weap.FindState("NormalToAlt"));
					}
				}
				else if ( !(player.cmd.buttons & BT_ALTATTACK) )
				{
					if ( tsp_weap.SetAltActive(false) )
					{
						player.SetPSprite(PSP_WEAPON, tsp_weap.FindState("AltToNormal"));
					}
				}
			}
			else
			{
				if ( player.cmd.buttons & BT_ALTATTACK )
				{
					if ( tsp_weap.ToggleAltActive() )
					{
						player.SetPSprite(PSP_WEAPON, tsp_weap.GetModSwapState());
					}
				}
			}
		}
		
		if ( TSP_TryNextMove() )
		{
			return;
		}

		// Check for fire. Some weapons do not auto fire.
		if ((player.WeaponState & WF_WEAPONREADY) && (player.cmd.buttons & BT_ATTACK))
		{
			if (!player.attackdown || !weapon.bNoAutofire)
			{
				player.attackdown = true;
				FireWeapon(NULL);
				return;
			}
		}
		/*else if ((player.WeaponState & WF_WEAPONREADYALT) && (player.cmd.buttons & BT_ALTATTACK))
		{
			if (!player.attackdown || !weapon.bNoAutofire)
			{
				player.attackdown = true;
				FireWeaponAlt (NULL);
				return;
			}
		}*/
		else
		{
			player.attackdown = false;
		}
	}
	
	override Weapon PickNextWeapon()
	{
		if(pp_switchingmod) return player.ReadyWeapon;
		return super.PickNextWeapon();
	}
	override Weapon PickPrevWeapon()
	{
		if(pp_switchingmod) return player.ReadyWeapon;
		return super.PickPrevWeapon();
	}
	override Weapon PickWeapon(int slot, bool checkammo)
	{
		if(pp_switchingmod) return player.ReadyWeapon;
		return super.PickWeapon(slot,checkammo);
	}
	
	void TSP_CycleModNext()
	{
		if(!(player.WeaponState & WF_WEAPONREADY || pp_switchingmod)) return;
		
		TSP_Weapon_Core currentWep = TSP_Weapon_Core(player.ReadyWeapon);
		if(currentWep == null) return;
		if(currentWep.bNoModSwitch) return;
		
		bool found;
		int slot;
		int index;
		if(pp_nextModSwitch!=null)
		{
			[found, slot, index] = player.weapons.LocateWeapon(pp_nextModSwitch.GetClass());
		}
		else
		{
			[found, slot, index] = player.weapons.LocateWeapon(currentWep.GetClass());
		}
		
		int indexSearch = index+1;
		int slotsSearched = 0;
		bool searchDone;
		while(slotsSearched<player.weapons.SlotSize(slot))
		{
			if(indexSearch>=player.weapons.SlotSize(slot))
			{
				indexSearch=0;
			}
			if(indexSearch==index) return;
			/*if ( pp_haveTheseWeapons.Find(player.weapons.GetWeapon(slot, indexSearch)) != pp_haveTheseWeapons.Size() )
			{
				searchDone = true;
				break;
			}*/
			indexSearch++;
			slotsSearched++;
		}
		
		if(!searchDone) return;
		
		let potentialWep = player.weapons.GetWeapon(slot, indexSearch);
		GiveInventory(potentialWep,1);
		
		pp_moddelay = 12;
		
		TSP_SwitchToMod(potentialWep);
	}
	
	void TSP_SwitchToMod(Class<Weapon> newMod)
	{
		TSP_Weapon_Core currentWep = TSP_Weapon_Core(player.ReadyWeapon);
		if(currentWep == null) return;
		if(currentWep.bNoModSwitch) return;
		if(!FindInventory(newMod)) return;
		pp_nextModSwitch = TSP_Weapon_Core(FindInventory(newMod));
		if(pp_nextModSwitch!=currentWep)
		{
			pp_nextModSwitch.tspw_powerlevel = currentWep.tspw_powerlevel;
			pp_nextModSwitch.tspw_ammolevel = currentWep.tspw_ammolevel;
			pp_nextModSwitch.tspw_reloadlevel = currentWep.tspw_reloadlevel;
			pp_nextModSwitch.tspw_curclip = currentWep.tspw_curclip;
			pp_nextModSwitch.tspw_clipsize = currentWep.tspw_clipsize;
		}
		player.PendingWeapon = pp_nextModSwitch;
		Console.Printf("");
		Console.Printf("");
		Console.Printf("");
		Console.Printf("Switching to "..pp_nextModSwitch.GetTag());
		pp_switchingmod = true;
	}
	
	override void CheckFOV()
	{
		super.CheckFOV();
		
		view_zoomLerp = view_zoomLerp + ( view_zoom - view_zoomLerp ) / 2;
		player.FOV = (player.DesiredFOV * view_zoomLerp);
	}
}