Class TSP_HitscanTracer : FastProjectile
{
	Default
	{
		Radius 1;
		Height 2;
		Speed 120;
		RenderStyle "Add";
		+BRIGHT
	}
	
	States
	{
		Spawn:
			POSS A -1;
			Stop;
	}
}


Class TSP_HitscanTracer_Enemy : TSP_HitscanTracer
{
	int tracerDamage;
	
	override int SpecialMissileHit (Actor victim)
	{
		victim.DamageMobj(self,target,tracerDamage,'Hitscan');
		return -1;
	}
	
	States
	{
		XDeath:
			TNT1 A 15 A_PlaySound("hit/flesh");
			Stop;
	}
}
