/*
	The Space Pirate
	Weapon Core
	
	Weapon essentials! This is what EVERY weapon should inherit from.
*/
const PSP_WEAPONANIM = 67;

Class TSP_MeleeTracer : LineTracer
{
    Actor toFind;
	bool foundFella;

    override ETraceStatus TraceCallback()
    {
		if ( toFind == null )
		{
            return TRACE_Stop;
		}
		
        if ( results.HitType == TRACE_HitActor )
        {
			if ( results.HitActor == toFind )
			{
				foundFella = true;
				return TRACE_Stop;
			}
            return TRACE_Skip;
        }

        return TRACE_Stop;
    }
}

Class TSP_NextMoveInfo
{
	State statetarget;
	int buttons;
	int held_buttons;
}

Class TSP_HitEffect play
{
	virtual void DoEffect(Actor victim)
	{
	}
}

Class TSP_HitEffect_Thrust : TSP_HitEffect
{
	Vector3 vel;
	
	static TSP_HitEffect Create(Actor newOwner, Vector3 newVel)
	{
		let newEffect = new("TSP_HitEffect_Thrust");
		double rotAngle = newOwner.angle;
		Vector2 rotbert = Actor.RotateVector(newVel.xy, rotAngle);
		newEffect.vel = (rotbert.x, rotbert.y, newVel.z);
		return newEffect;
	}
	
	override void DoEffect(Actor victim)
	{
		if ( victim.bDONTTHRUST ) return;
		victim.vel += vel;
	}
}

Class TSP_HitEffect_Stun : TSP_HitEffect
{
	int tics;
	
	static TSP_HitEffect Create(Actor newOwner, int newTics)
	{
		let newEffect = new("TSP_HitEffect_Stun");
		newEffect.tics = newTics;
		return newEffect;
	}
	
	override void DoEffect(Actor victim)
	{
		victim.tics += tics;
	}
}

Class TSP_HitEffect_Cleave : TSP_HitEffect
{
	int radius;
	int damage;
	Actor og;
	
	bool didCleave;
	
	static TSP_HitEffect Create(Actor newOwner, int newRadius, int newDamage)
	{
		let newEffect = new("TSP_HitEffect_Cleave");
		newEffect.og = newOwner;
		newEffect.radius = newRadius;
		newEffect.damage = newDamage;
		return newEffect;
	}
	
	override void DoEffect(Actor victim)
	{
		if ( didCleave ) return;
		
		BlockThingsIterator it = BlockThingsIterator.Create(victim, radius);
		Actor mo;
		bool hitSomething;
		
		let tracer = new('TSP_MeleeTracer');
		
		while ( it.Next() )
		{
			mo = it.thing;
			
			if ( mo == og ) continue;
			if ( !mo.bShootable || mo.bDormant || mo.Health <= 0 ) continue;
			
			Vector3 diff = mo.pos - og.pos;
			
			tracer.Trace(og.pos + (0,0,og.height/2), og.cursector, diff.Unit(), radius, TRACE_HitSky, Line.ML_BLOCKEVERYTHING, false, og);
			let res = tracer.results;
				
			if ( res.HitActor == null ) continue;
			if ( res.HitActor != mo ) continue;
			
			mo.DamageMobj(og, og, damage, 'Explosion');
			mo.tics += 5;
			mo.vel = (diff+(0,0,4)).Unit() * 12;
		}
	}
}

Class TSP_BaseWeapon : Weapon
{
	int tsp_modflags;
	
	flagdef HoldForMod: tsp_modflags, 1;
	
	Default
	{
		Weapon.WeaponScaleY 1.0;
	}
	
	States
	{
		QuickMelee:
			TNT1 A 0
			{
				A_SelectWeapon("TSP_Weapon_MelFists");
				return resolveState("Deselect");
			}
			Wait;
	}
	
	bool alt_active;
	int mod_cooldown;
	
	Array<Actor> melee_victims;
	Array<TSP_NextMoveInfo> nextmoves;
	
	bool SetAltActive (bool newvalue)
	{
		if ( newValue != alt_active )
		{
			if ( newValue && !FindState('AltReady') )
			{
				return false;
			}
			alt_active = newValue;
			return true;
		}
		return false;
	}
	
	bool ToggleAltActive ()
	{
		if ( mod_cooldown > 0 ) return false;
		
		if ( SetAltActive(!alt_active) )
		{
			mod_cooldown = 12;
			return true;
		}
		
		return false;
	}
	
	override void Tick()
	{
		super.Tick();
		
		if ( !owner ) return;
		
		if ( mod_cooldown > 0 )
		{
			mod_cooldown -= 1;
		}
	}
	
	override State GetReadyState()
	{
		let player = owner.player;
		if ( alt_active && FindState('AltReady') )
		{
			return FindState('AltReady');
		}
		return FindState('Ready');
	}
	
	override State GetAtkState(bool hold)
	{
		let player = owner.player;
		if ( alt_active && FindState('AltFire') )
		{
			return FindState('AltFire');
		}
		return FindState('Fire');
	}
	
	virtual State GetModSwapState()
	{
		let player = owner.player;
		if ( alt_active )
		{
			return FindState('NormalToAlt');
		}
		return FindState('AltToNormal');
	}
	
	action void A_TSP_WeaponReady(int flags = 0)
	{
		A_TSP_ClearNextStates();
		A_WeaponReady(flags);
	}
	
	/*
		A_TSP_GotoReady()
		
		Automatically raises the weapon so you don't gotta deal with A_Raise() shenanigans.
	*/
	
		action State A_TSP_GotoReady()
		{
			return invoker.GetReadyState();
		}
	
	/*
		A_TSP_Select()
		
		Automatically raises the weapon so you don't gotta deal with A_Raise() shenanigans.
	*/
	
		action void A_TSP_Select()
		{
			A_TSP_ZoomFactor(1.0);
			A_WeaponOffset(0, 32);
		}
	
	/*
		A_TSP_Deselect()
		
		Ditto, but for lowering.
	*/
	
		action void A_TSP_Deselect()
		{
			invoker.alt_active = false;
			A_TSP_ZoomFactor(1.0);
			A_Lower(420);
		}
	
	/*
		A_TSP_SetNextFireState()
	*/
	
		action void A_TSP_AddNextState(StateLabel st, int buttons = BT_ATTACK, int held_buttons = false)
		{
			let nextmove = new("TSP_NextMoveInfo");
			nextmove.buttons = buttons;
			nextmove.statetarget = resolveState(st);
			nextmove.held_buttons = held_buttons;
			invoker.nextmoves.Push(nextmove);
		}

		action void A_TSP_ClearNextStates()
		{
			invoker.nextmoves.Clear();
		}
		
		action void A_TSP_SetNextState(StateLabel st, int buttons = BT_ATTACK, int held_buttons = 0)
		{
			A_TSP_ClearNextStates();
			A_TSP_AddNextState(st, buttons, held_buttons);
		}
	
	/*
		A_TSP_HitStop()
	*/
	
		action void A_TSP_HitStop(int pausetics, int radius)
		{
			BlockThingsIterator it = BlockThingsIterator.Create(self, radius);
			Actor mo;
			
			Actor src = invoker.owner;
			let player = TSP_PlayerPawn_ZSCBase(src);
			
			while ( it.Next() )
			{
				mo = it.thing;
				if ( mo == src ) continue;
				
				Vector3 diff = mo.pos - src.pos;
				if ( diff.length() > radius ) continue;
				
				if ( mo.health > 0 && mo.tics > 0 )
				{
					mo.tics += pausetics;
				}
			}
		}
		
	/*
	*/
	
		action void A_TSP_ApplyToVictims(TSP_HitEffect effect)
		{
			for ( int i = 0; i < invoker.melee_victims.size(); i++ )
			{
				Actor mo = invoker.melee_victims[i];
				if ( mo == null ) continue;
				effect.DoEffect(mo);
			}			
		}
		
	/*
		A_TSP_AddRecoil()
	*/
	
		action void A_TSP_AddRecoil (TSP_ViewRecoil newRecoil)
		{
			Actor src = invoker.owner;
			let player = TSP_PlayerPawn_ZSCBase(src);
			player.AddRecoil(newRecoil);
		}
	
		action void A_TSP_AddBumper (TSP_SpriteBumper newBumper)
		{
			Actor src = invoker.owner;
			let player = TSP_PlayerPawn_ZSCBase(src);
			player.AddBumper(newBumper);
		}
		
	/*
		A_TSP_ZoomFactor()
	*/
	
		action void A_TSP_ZoomFactor (double scale = 1.0)
		{
			Actor src = invoker.owner;
			let player = TSP_PlayerPawn_ZSCBase(src);
			player.view_zoom = scale;
		}
		
	/*
		A_TSP_Melee()
	*/
	
		action bool A_TSP_Melee(int dmg, int range = 72, int maxAngle = -1, int flags = 0, Name damageType = 'Melee')
		{
			invoker.melee_victims.Clear();
			
			Actor src = invoker.owner;
			
			BlockThingsIterator it = BlockThingsIterator.Create(src, range);
			Actor mo;
			bool hitSomething;
			
			let player = TSP_PlayerPawn_ZSCBase(src);
			
			let tracer = new('TSP_MeleeTracer');
			
			while ( it.Next() )
			{
				mo = it.thing;
				if ( !mo.bShootable || mo.bDormant || mo.Health <= 0 ) continue; // Bro are you even alive... r u breathing???
				if ( maxAngle != -1 && AbsAngle(src.angle, src.AngleTo(mo)) > maxAngle ) continue; // Within acceptable angles
				
				Vector3 diff = mo.pos - src.pos;
				
				tracer.toFind = mo;
				tracer.Trace(src.pos + (0,0,src.height/2), src.cursector, diff.Unit(), range, TRACE_HitSky, Line.ML_BLOCKEVERYTHING, false, self);
				let res = tracer.results;
				
				if ( res.HitActor == null ) continue;
				if ( res.HitActor != mo ) continue;
				
				mo.DamageMobj(src, src, dmg, damageType);
				mo.TriggerPainChance(damageType, true);
				hitSomething = true;
				invoker.melee_victims.Push(mo);
			}
			
			if ( hitSomething )
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.duration = 2;
				recoil.shake_amount = 1;
				player.AddRecoil(recoil);
				int freezeAmt = clamp(double(dmg)/10.0, 1.0, 8.0);
				A_TSP_HitStop(freezeAmt, 256);
				A_StartSound("melee/basic/normal/impact", CHAN_WEAPON);
				player.SetHitFreeze(freezeAmt);
			}
			else
			{
				tracer.toFind = null;
				Vector3 spawnPos = (src.pos.x, src.pos.y, src.player.viewz);
				Quat base = Quat.FromAngles(src.angle, src.pitch, src.roll);
				Vector3 forward = (1,0,0);
				tracer.Trace(spawnPos, src.cursector, base * forward, range, TRACE_HitSky, Line.ML_BLOCKEVERYTHING, false, self);
				let res = tracer.results;
				if ( res.HitType != TRACE_HitNone )
				{
					let fx = Spawn("TSP_MeleeImpactFX", res.HitPos - res.HitVector*0.5);
					if ( res.HitType == Trace_HitWall )
					{
						fx.bWALLSPRITE = true;
						let line = res.HitLine;
						fx.angle = atan2(line.delta.y, line.delta.x)+90;
					}
					//S_StartSoundAt(res.HitPos, "melee/basic/normal/wall", CHAN_WEAPON);
					A_StartSound("melee/basic/normal/wall", CHAN_WEAPON);
					let recoil = new("TSP_ViewRecoil");
					recoil.duration = 2;
					recoil.shake_amount = 0.75;
					player.AddRecoil(recoil);
				}
			}
			
			return hitSomething;
		}
		
	/*
		A_TSP_FireBullets()
		
		Standard bullet firing stuff. Compared to the vanilla Doom bullet shenanigans,
		this one uses quaternions to solve gimbal locking and fires directly
		from the player's viewpoint. TSP is finally a AAA game...
		
		The hitscan itself is purely from the player's viewpoint, but tracers
		are slightly offset.
	*/
	
		action void A_TSP_FireBullets(double spread_h, double spread_v, int amount, int damage, Vector3 tracerOffset = (0,-8,-8))
		{
			let owner = PlayerPawn(invoker.owner);
			Vector3 spawnPos = (owner.pos.x, owner.pos.y, owner.player.viewz);
		
			Quat base = Quat.FromAngles(owner.angle, owner.pitch, owner.roll);
			Vector3 forward = (1,0,0);
			
			//Vector3 tracerOffset = (0, -8, -8);
			Vector3 tracerPos = spawnPos + (base * tracerOffset);
		
			for ( int i = 0; i < abs(amount); i++ )
			{
				double spreadX = frandom(0, spread_h);
				double spreadY = frandom(0, spread_v);
				double rot = frandom(0, 360);
				Quat offset = Quat.AxisAngle((0,0,1), spreadX*cos(rot));
				offset = offset * Quat.AxisAngle((0,1,0), spreadY*sin(rot));
				Vector3 dir = base * offset * forward;
				
				double aimYaw = atan2(dir.y, dir.x);
				double aimPitch = -asin(dir.z);
				
				FLineTraceData tr;
				owner.LineTrace(aimYaw, PLAYERMISSILERANGE, aimPitch, flags: TRF_ABSPOSITION, offsetz: spawnPos.z, offsetforward: spawnPos.x, offsetside: spawnPos.y, data: tr);
				
				bool thruPortal = (tr.NumPortals > 0);
				
				Actor puff = LineAttack(aimYaw, PLAYERMISSILERANGE, aimPitch, damage, 'Hitscan', "TSP_BulletPuff",
					flags: LAF_ABSPOSITION, offsetz: spawnPos.z, offsetforward: spawnPos.x, offsetside: spawnPos.y);
				
				let tracer = TSP_HitscanTracerFX(Spawn("TSP_HitscanTracerFX", tracerPos));
				
				// [Py] only try to follow the puff IF it's not through a portal. why? agony
				if ( puff )
				{
					if ( !thruPortal )
					{
						Vector3 traceDiff = level.Vec3Diff(tracerPos, puff.pos).Unit();
						aimYaw = atan2(traceDiff.y, traceDiff.x);
						aimPitch = -asin(traceDiff.z);
					}
				}
				
				owner.LineTrace(aimYaw, PLAYERMISSILERANGE, aimPitch, flags: TRF_ABSPOSITION, offsetz: tracerPos.z, offsetforward: tracerPos.x, offsetside: tracerPos.y, data: tr);
				
				Vector3 moveDir = tr.HitDir;
				
				tracer.owner = invoker.owner;
				tracer.angle = atan2(moveDir.y, moveDir.x);
				tracer.pitch = -asin(moveDir.z);
				tracer.moveDir = moveDir;
				
				tracer.Init();
			}
		}
		
	/*
	*/
	
	action void A_TSP_QuickMelee()
	{
		A_TSP_Melee(10);
		
		TSP_HitEffect fx_thrust = TSP_HitEffect_Thrust.Create(invoker.owner, (7,0,1));
		A_TSP_ApplyToVictims(fx_thrust);
		
		TSP_HitEffect fx_stun = TSP_HitEffect_Stun.Create(invoker.owner, 4);
		A_TSP_ApplyToVictims(fx_stun);
	}
}