/*
	The Space Pirate
	Weapon Core
	
	Weapon essentials! This is what EVERY weapon should inherit from.
*/

Class TSP_MeleeTracer : LineTracer
{
    Actor toFind;
	bool foundFella;

    override ETraceStatus TraceCallback()
    {
		if ( toFind == null )
		{
            return TRACE_Stop;
		}
		
        if ( results.HitType == TRACE_HitActor && results.HitActor == toFind )
        {
			foundFella = true;
            return TRACE_Stop;
        }

        return TRACE_Skip;
    }
}

Class TSP_NextMoveInfo
{
	State statetarget;
	int buttons;
	bool isHeld;
}

Class TSP_BaseWeapon : Weapon
{
	Default
	{
		Weapon.WeaponScaleY 1.0;
	}
	
	Array<Actor> melee_victims;
	Array<TSP_NextMoveInfo> nextmoves;
	
		action void A_TSP_WeaponReady(int flags = 0)
		{
			A_TSP_ClearNextStates();
			A_WeaponReady(flags);
		}
	
	/*
		A_TSP_Select()
		
		Automatically raises the weapon so you don't gotta deal with A_Raise() shenanigans.
	*/
	
		action void A_TSP_Select()
		{
			A_WeaponOffset(0, 32);
		}
	
	/*
		A_TSP_Deselect()
		
		Ditto, but for lowering.
	*/
	
		action void A_TSP_Deselect()
		{
			A_Lower(420);
		}
	
	/*
		A_TSP_SetNextFireState()
	*/
	
	action void A_TSP_AddNextState(StateLabel st, int buttons = BT_ATTACK, bool isHeld = false)
	{
		let nextmove = new("TSP_NextMoveInfo");
		nextmove.buttons = buttons;
		nextmove.statetarget = resolveState(st);
		nextmove.isHeld = isHeld;
		invoker.nextmoves.Push(nextmove);
	}

	action void A_TSP_ClearNextStates()
	{
		invoker.nextmoves.Clear();
	}
	
	/*
		A_TSP_HitStop()
	*/
	
		action void A_TSP_HitStop(int pausetics, int radius)
		{
			BlockThingsIterator it = BlockThingsIterator.Create(self, radius);
			Actor mo;
			
			Actor src = invoker.owner;
			let player = TSP_PlayerPawn_ZSCBase(src);
			
			while ( it.Next() )
			{
				mo = it.thing;
				if ( mo == src ) continue;
				
				Vector3 diff = mo.pos - src.pos;
				if ( diff.length() > radius ) continue;
				
				if ( mo.health > 0 && mo.tics > 0 )
				{
					mo.tics += pausetics;
				}
			}
		}
		
	/*
		A_TSP_AddRecoil()
	*/
	
		action void A_TSP_AddRecoil (TSP_ViewRecoil newRecoil)
		{
			Actor src = invoker.owner;
			let player = TSP_PlayerPawn_ZSCBase(src);
			player.AddRecoil(newRecoil);
		}
		
	/*
		A_TSP_Melee()
	*/
	
		action bool A_TSP_Melee(int dmg, int range = 72, int maxAngle = -1, int flags = 0, Name damageType = 'Melee')
		{
			invoker.melee_victims.Clear();
			
			BlockThingsIterator it = BlockThingsIterator.Create(self, range);
			Actor mo;
			bool hitSomething;
			
			Actor src = invoker.owner;
			let player = TSP_PlayerPawn_ZSCBase(src);
			
			let tracer = new('TSP_MeleeTracer');
			
			while ( it.Next() )
			{
				mo = it.thing;
				if ( !mo.bShootable || mo.bDormant || mo.Health <= 0 ) continue; // Bro are you even alive... r u breathing???
				if ( maxAngle != -1 && AbsAngle(src.angle, src.AngleTo(mo)) > maxAngle ) continue; // Within acceptable angles
				
				Vector3 diff = mo.pos - src.pos;
				
				tracer.toFind = mo;
				tracer.Trace(src.pos + (0,0,src.height/2), src.cursector, diff.Unit(), range, TRACE_HitSky, Line.ML_BLOCKEVERYTHING, false, self);
				let res = tracer.results;
				
				if ( res.HitActor == null ) continue;
				if ( res.HitActor != mo ) continue;
				
				mo.DamageMobj(src, src, dmg, damageType);
				mo.TriggerPainChance(damageType, true);
				hitSomething = true;
				invoker.melee_victims.Push(mo);
			}
			
			if ( hitSomething )
			{
				let recoil = new("TSP_ViewRecoil");
				recoil.duration = 2;
				recoil.shake_amount = 1;
				player.AddRecoil(recoil);
				int freezeAmt = clamp(double(dmg)/5.0, 2.0, 8.0);
				A_TSP_HitStop(freezeAmt, 256);
				A_StartSound("melee/basic/normal/impact", CHAN_WEAPON);
				player.SetHitFreeze(freezeAmt);
			}
			else
			{
				tracer.toFind = null;
				Vector3 spawnPos = (src.pos.x, src.pos.y, src.player.viewz);
				Quat base = Quat.FromAngles(src.angle, src.pitch, src.roll);
				Vector3 forward = (1,0,0);
				tracer.Trace(spawnPos, src.cursector, base * forward, range, TRACE_HitSky, Line.ML_BLOCKEVERYTHING, false, self);
				let res = tracer.results;
				if ( res.HitType != TRACE_HitNone )
				{
					let fx = Spawn("TSP_MeleeImpactFX", res.HitPos - res.HitVector*0.5);
					if ( res.HitType == Trace_HitWall )
					{
						fx.bWALLSPRITE = true;
						let line = res.HitLine;
						fx.angle = atan2(line.delta.y, line.delta.x)+90;
					}
					//S_StartSoundAt(res.HitPos, "melee/basic/normal/wall", CHAN_WEAPON);
					A_StartSound("melee/basic/normal/wall", CHAN_WEAPON);
					let recoil = new("TSP_ViewRecoil");
					recoil.duration = 2;
					recoil.shake_amount = 0.75;
					player.AddRecoil(recoil);
				}
			}
			
			return hitSomething;
		}
		
	/*
		A_TSP_FireBullets()
		
		Standard bullet firing stuff. Compared to the vanilla Doom bullet shenanigans,
		this one uses quaternions to solve gimbal locking and fires directly
		from the player's viewpoint. TSP is finally a AAA game...
		
		The hitscan itself is purely from the player's viewpoint, but tracers
		are slightly offset.
	*/
	
		action void A_TSP_FireBullets(double spread_h, double spread_v, int amount, int damage)
		{
			let owner = PlayerPawn(invoker.owner);
			Vector3 spawnPos = (owner.pos.x, owner.pos.y, owner.player.viewz);
		
			Quat base = Quat.FromAngles(owner.angle, owner.pitch, owner.roll);
			Vector3 forward = (1,0,0);
		
			for ( int i = 0; i < abs(amount); i++ )
			{
				double spreadX = frandom(0, spread_h);
				double spreadY = frandom(0, spread_v);
				double rot  = frandom(0, 360);
				Quat offset = Quat.AxisAngle((0,0,1), spreadX*cos(rot));
				offset = offset * Quat.AxisAngle((0,1,0), spreadY*sin(rot));
				Vector3 dir = base * offset * forward;
				
				double aimYaw = atan2(dir.y, dir.x);
				double aimPitch = -asin(dir.z);
				
				LineAttack(aimYaw, PLAYERMISSILERANGE, aimPitch, damage, 'Hitscan', "TSP_BulletPuff",
					flags: LAF_ABSPOSITION, offsetz: spawnPos.z, offsetforward: spawnPos.x, offsetside: spawnPos.y);
			}
		}
}