Class TSP_UpgradeBase : Inventory
{
	Default
	{
		Inventory.Amount 1;
	}
	
	virtual void UpgradeEffect(Actor victim)
	{
	}
}

Class TSP_Upgrade_MagSling : TSP_UpgradeBase {}

Class TSP_Upgrade_Shield : TSP_UpgradeBase
{
	Default
	{
		Inventory.MaxAmount 3;
	}
	
	override void UpgradeEffect(Actor victim)
	{
		victim.GiveInventory("TSP_PlayerPawn_MaxShield",25);
		//Console.Printf("\ccYour shield is enhanced further... [\cf"..victim.CountInv("TSP_PlayerPawn_MaxShield").."\cc]");
	}
}