enum ETSPWeaponSlot
{
	WEAPONSLOT_FISTS,
	WEAPONSLOT_PISTOL,
	WEAPONSLOT_SHOTGUN,
	WEAPONSLOT_SUPERSHOTGUN,
	WEAPONSLOT_CHAINGUN,
	WEAPONSLOT_ROCKETLAUNCHER,
	WEAPONSLOT_PLASMARIFLE,
	WEAPONSLOT_BFG9000,
}

Class TSP_WeaponPickup : Inventory
{
	int slottogive;
	
	Property SlotToGive : slottogive;
	
	Default
	{
		Inventory.PickupSound "general/weaponpickup";
	}
	
	override void PostBeginPlay()
	{
		super.PostBeginPlay();
		
		Class<Weapon> cls = TSP_PlayerPawn_ZSCBase(players[consoleplayer].mo).GetWeaponPickupClass(slottogive);
		
		if ( !cls ) return;
		
		let newState = GetDefaultByType(cls).FindState("Spawn");
		
		SetState(newState);
	}
	
	override bool TryPickup (in out Actor other)
	{
		if ( other.player == null ) return false;
		
		let player = TSP_PlayerPawn_ZSCBase(other.player.mo);
		if ( player.GiveWeaponPickup(slottogive) )
		{
			GoAwayAndDie();
			return true;
		}
		return false;
	}
}

// PISTOLS

Class TSP_Pickup_Pistol : TSP_WeaponPickup replaces Pistol
{
	Default
	{
		TSP_WeaponPickup.SlotToGive WEAPONSLOT_PISTOL;
	}
	
	States
	{
		Spawn:
			121P A -1;
			Stop;
	}
}

Class TSP_Pickup_Shotgun : TSP_WeaponPickup replaces Shotgun
{
	Default
	{
		TSP_WeaponPickup.SlotToGive WEAPONSLOT_SHOTGUN;
	}
	
	States
	{
		Spawn:
			131P A -1;
			Stop;
	}
}

Class TSP_Pickup_SuperShotgun : TSP_WeaponPickup replaces SuperShotgun
{
	Default
	{
		TSP_WeaponPickup.SlotToGive WEAPONSLOT_SUPERSHOTGUN;
	}
	
	States
	{
		Spawn:
			131P A -1;
			Stop;
	}
}

Class TSP_Pickup_Chaingun : TSP_WeaponPickup replaces Chaingun
{
	Default
	{
		TSP_WeaponPickup.SlotToGive WEAPONSLOT_CHAINGUN;
	}
	
	States
	{
		Spawn:
			131P A -1;
			Stop;
	}
}

Class TSP_Pickup_RocketLauncher : TSP_WeaponPickup replaces RocketLauncher
{
	Default
	{
		TSP_WeaponPickup.SlotToGive WEAPONSLOT_ROCKETLAUNCHER;
	}
	
	States
	{
		Spawn:
			131P A -1;
			Stop;
	}
}

Class TSP_Pickup_PlasmaRifle : TSP_WeaponPickup replaces PlasmaRifle
{
	Default
	{
		TSP_WeaponPickup.SlotToGive WEAPONSLOT_PLASMARIFLE;
	}
	
	States
	{
		Spawn:
			131P A -1;
			Stop;
	}
}

Class TSP_Pickup_BFG9000 : TSP_WeaponPickup replaces BFG9000
{
	Default
	{
		TSP_WeaponPickup.SlotToGive WEAPONSLOT_BFG9000;
	}
	
	States
	{
		Spawn:
			131P A -1;
			Stop;
	}
}