Class TSP_BountyHunterSpawn
{
	Class<Actor> monster;
	int weight;
	
	int spawn_start;
	int spawn_end;
	int spawn_fadein;
	int spawn_fadeout;
}

Class TSP_GameModeThinker : Thinker
{
	virtual void WorldThingDied (WorldEvent e)
	{
	}
	
	virtual ui int DrawHUD (TSP_StatusBar sbar, double ticFrac)
	{
		return 0;
	}
}

Class TSP_GameMode_BountyHunters : TSP_GameModeThinker
{
	Array<TSP_BountyHunterSpawn> spawns;
	Array<TSP_BountyHunters_EnemySpawn> spawnpoints;
	
	int time_nextspawn;
	
	int wave;
	int spawns_left;
	int monsters_active;
	int wave_kills;
	
	int time_left;
	
	const SPAWNSPERWAVE = 10;
	const MAXMONSTERS = 20;
	const KILLSTOPASS = 5;
	
	void AddTime (int secs)
	{
		time_left += secs*35;
		S_StartSound("ailene/bh/timeadded", CHAN_VOICE);
	}
	
	void TrySpawn()
	{
		Array<TSP_BountyHunterSpawn> spawninfo;
		int maxWeight = 0;
		for ( int i = 0; i < spawns.Size(); i++ )
		{
			if ( spawns[i].spawn_start != 0 && wave < spawns[i].spawn_start )
			{
				continue;
			}
			if ( spawns[i].spawn_end != 0 && wave >= spawns[i].spawn_end )
			{
				continue;
			}
			maxWeight += spawns[i].weight;
			spawninfo.Push(spawns[i]);
		}
		
		int weight = random(0, maxWeight);
		Console.Printf(""..weight.." / "..maxWeight);
		
		for ( int i = 0; i < spawninfo.Size(); i++ )
		{
			weight -= spawninfo[i].weight;
			
			if ( weight <= 0 )
			{
				Vector3 newSpawn = GetSpawnPoint();
				let foe = Actor.Spawn(spawninfo[i].monster, newSpawn);
				foe.target = players[0].mo;
				foe.SetState(foe.SeeState);
				monsters_active += 1;
				Console.Printf("Spawning "..spawninfo[i].monster.GetClassName());
				break;
			}
		}
	}
	
	Vector3 GetSpawnPoint()
	{
		int size = spawnpoints.Size();

		for ( int i = 0; i < size; i++ )
		{
			int j = random(0, i);
			
			let temp = spawnpoints[i];
			spawnpoints[i] = spawnpoints[j];
			spawnpoints[j] = temp;
		}

		for ( int i = 0; i < size; i++ )
		{
			double diff = (players[0].mo.pos - spawnpoints[i].pos).Length();
			if ( diff < 1024 || diff > 2048 )
			{
				continue;
			}
			//Console.Printf("y "..diff);
			return spawnpoints[i].pos;
		}
		//Console.Printf("n");
		return spawnpoints[random(0,size-1)].pos;
	}
	
	override void PostBeginPlay()
	{
		ThinkerIterator it = ThinkerIterator.Create("TSP_BountyHunters_EnemySpawn");
		TSP_BountyHunters_EnemySpawn mo;
		while ( mo = TSP_BountyHunters_EnemySpawn(it.Next()) )
		{
			spawnpoints.Push(mo);
		}
		
		spawns_left = SPAWNSPERWAVE;
		
		TSP_BountyHunterSpawn spawn;
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "ZombieMan";
		spawn.spawn_start = 0;
		spawn.spawn_end = 7;
		spawn.weight = 200;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "ShotgunGuy";
		spawn.spawn_start = 1;
		spawn.spawn_end = 12;
		spawn.weight = 100;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "ChaingunGuy";
		spawn.spawn_start = 5;
		spawn.weight = 50;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "DoomImp";
		spawn.spawn_start = 2;
		spawn.weight = 200;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "Demon";
		spawn.spawn_start = 3;
		spawn.weight = 100;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "HellKnight";
		spawn.spawn_start = 5;
		spawn.weight = 100;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "Cacodemon";
		spawn.spawn_start = 7;
		spawn.weight = 75;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "Revenant";
		spawn.spawn_start = 8;
		spawn.weight = 50;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "BaronOfhell";
		spawn.spawn_start = 9;
		spawn.weight = 50;
		spawns.Push(spawn);
		
		spawn = new("TSP_BountyHunterSpawn");
		spawn.monster = "Archvile";
		spawn.spawn_start = 10;
		spawn.weight = 25;
		spawns.Push(spawn);
		
		time_left = 35*45;
	}
	
	override void Tick()
	{
		if ( spawnpoints.Size() == 0 ) return;
		
		if ( level.maptime >= time_nextspawn )
		{
			time_nextspawn = level.maptime+35;
			if ( monsters_active < MAXMONSTERS && spawns_left > 0 )
			{
				TrySpawn();
				spawns_left -= 1;
			}
		}
		
		time_left -= 1;
		
		if ( time_left <= 0 )
		{
			players[0].mo.A_Die();
		}
		
		switch ( time_left-30 )
		{
			case (30*35):
				S_StartSound("ailene/bh/30secs", CHAN_VOICE);
				break;
			case (15*35):
				S_StartSound("ailene/bh/10secs", CHAN_VOICE);
				break;
			case (3*35):
				S_StartSound("ailene/bh/3secs", CHAN_VOICE);
				break;
			case (2*35):
				S_StartSound("ailene/bh/2secs", CHAN_VOICE);
				break;
			case (1*35):
				S_StartSound("ailene/bh/1secs", CHAN_VOICE);
				break;
		}
	}
	
	override void WorldThingDied (WorldEvent e)
	{
		if ( e.Thing.bCOUNTKILL )
		{
			monsters_active -= 1;
			wave_kills += 1;
			if ( spawns_left <= 0 && wave_kills >= KILLSTOPASS )
			{
				spawns_left = SPAWNSPERWAVE;
				wave += 1;
				wave_kills = 0;
				time_nextspawn = level.maptime + (35*4);
				Console.Printf("Next wave lel");
			}
		}
	}
	
	override int DrawHUD (TSP_StatusBar sbar, double ticFrac)
	{
		TSPUI.DrawText(640, 4, "\ckTime Left:", size: 20, align: 0);
		TSPUI.DrawText(640, 14, "\ct"..int(time_left/35.), size: 48, align: 0);
		
		return 64;
	}
}

Class TSP_BountyHunters_LevelEditor : LevelPostProcessor
{
	bool IsTypeClose (int og, int check, int dist)
	{
		Vector3 oldPos = GetThingPos(og);
		for ( int i = 0; i < GetThingCount(); i++ )
		{
			if ( GetThingEdNum(i) != check ) continue;
			
			if ( (oldPos - GetThingPos(i)).Length() < dist )
			{
				return true;
			}
		}
		return false;
	}
	
	protected void Apply(Name checksum, String mapname)
	{
		if ( _tsp_tempgm == 1 )
		{
			for ( int i = 0; i < GetThingCount(); i++ )
			{
				switch ( GetThingEdNum(i) )
				{
					case 82:
					case 2001:
					case 2002:
					case 2003:
					case 2004:
					case 2005:
					case 2006:
					case 5010:
						if ( !IsTypeClose(i, 11, 64) && !IsTypeClose(i, 24800, 64) )
						{
							SetThingEdNum(i, 8008135);
							SetThingFlags(i, MTF_SINGLE);
						}
						else
						{
							SetThingFlags(i, 0);
						}
						break;
					case 11:
						SetThingEdNum(i, 24800);
						SetThingFlags(i, MTF_SINGLE);
						break;
				}
			}
		}
	}
}