Class TSP_TitleHandler : EventHandler
{
	int titleFrame;
	
	override void WorldLoaded(WorldEvent e)
	{
		titleFrame = -12;
	}
	
	override void WorldTick()
	{
		if ( titleFrame < 105 )
		{
			titleFrame++;
		}
	}
	
	override void RenderOverlay(RenderEvent e)
	{
		if ( titleFrame >= 5 )
		{
			let titlePic = TexMan.CheckForTexture("graphics/title/titleanim_"..titleFrame..".png");
			
			Screen.DrawTexture(titlePic, false, 160, 120,
				DTA_VirtualWidth, 320, DTA_VirtualHeight, 240);
		}
	}
}